### ISSUE TITLE
Python doesn't require `vc` package

### ISSUE THREAD

**Issue by tadeu** [conda-forge/python-feedstock#104]
Regarding the [VC features](https://github.com/conda-forge/staged-recipes/wiki/VC-features), the `python` package is not requiring the `vc` package ([recipe](https://github.com/conda-forge/python-feedstock/blob/master/recipe/meta.yaml)), so, for example, it is allowed to install `python 3.5` side-by-side with the `vc 10` package, so both `vc14` and `vc10` features would be tracked.

What's the idea? Can this block be added to the python recipe?

```yaml
requirements:
  build:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
```
