### ISSUE TITLE
Make recipe friendlier to those that build off it

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/python-feedstock#578]
### Comment:

I maintain python for my company and we try to stay close to the conda-forge recipe. We aim to be compatible with conda-forge rather than defaults.

However, things like

```yaml
      string: {{ dev_ }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}{{ linkage_nature }}{{ debug }}_cpython  # ["conda-forge" in (channel_targets or "")]
      string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}{{ linkage_nature }}{{ debug }}  # ["conda-forge" not in (channel_targets or "")]
{% if 'conda-forge' in channel_targets %}
      run_exports:
        noarch:
          - python
        weak:
          - python_abi {{ ver2 }}.* *_cp{{ ver2nd }}
{% endif %}
```

Link: main as of 2022/08/31 https://github.com/conda-forge/python-feedstock/blob/134ba25ba2f5696c14060518fafb4aaebfedb544/recipe/meta.yaml#L128

My guess is that this syntax was introduced to be compatible with AnacondaRecipes.

Package for me often fail to install with our built version of python, because they are looking for something with a build ending in `_cpython`.

I'm wondering if we can work to find a syntax that is more generalizable to other people building off the conda-forge recipe as well.
